--
-- PostgreSQL database dump
--

\restrict hYrHpNzxhR0eNNrFOIGAWNmlhwMYBBXbZxVwa3IEjmtLmBGGplzHE27y9YHp9Zf

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: inspection_report; Type: TABLE DATA; Schema: botzilla; Owner: marce
--

INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (276, 144, 9291, 'Marce', 'Marcelo Sznek', 'Marce  Marce', '1234', 'marce@gmail.com', '6868 SW 8th St, Miami, FL 33144', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=9291&page=viewInspectionReport', 'cement_tiles', 'plywood', 'between_5_and_10_years', 'false', 'needs_replacement', false, 'moderate', 'between_5_and_10_years', 'fair', 'good', true, true, true, '2025-09-26 10:57:44.531-03', '2025-09-26 12:35:06.018-03', '2025-09-26 12:35:06.021-03', 'marcelosz.office@gmail.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (275, 145, 10649, 'Christopher J Steele-Roof ', 'Rick Apodaca', 'Christopher Steele', '714-313-4474', 'chris.steele@yahoo.com', '3251 Mainway Dr, Los Alamitos, CA 90720', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10649&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'over_20_years', 'true', 'needs_replacement', true, 'high', 'less_than_5_years', 'good', 'good', false, true, false, '2025-09-26 11:19:04.57-03', '2025-09-26 12:35:06.008-03', '2025-09-26 15:50:59.387-03', 'rapodaca@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (273, 147, 10650, 'Lauri Huston - BHAM ', 'William Gwinn', 'Lauri Huston', '206-818-8008', 'lauri@sanjuansailing.com', '3315 Northshore Rd, Bellingham, WA 98226', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10650&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_11_and_20_years', 'true', 'good', false, 'high', 'less_than_5_years', NULL, NULL, false, false, false, '2025-09-26 12:12:37.225-03', '2025-09-26 12:35:05.986-03', '2025-09-26 12:35:05.986-03', 'wgwinn@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (277, 142, 10010, 'Marcelo testing', 'Marcelo Sznek', 'Marcelo Ariel Sznek', '1171624859', 'marce@gmail.com', '6868 SW Terwilliger Blvd, Portland, OR 97219', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10010&page=viewInspectionReport', 'clay_tiles', 'plywood', 'between_5_and_10_years', 'false', 'good', true, 'high', 'between_5_and_10_years', 'fair', 'fair', false, true, true, '2025-09-26 10:56:41.192-03', '2025-09-26 12:35:06.025-03', '2025-09-26 12:35:06.027-03', 'marcelosz.office@gmail.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (278, 140, 2, 'Patricia Gonzalez - BUR', 'Brian Rayburn', 'Patricia Gonzalez', NULL, NULL, '4406 N Clybourn Ave, Burbank, CA 91505', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=2&page=viewInspectionReport', 'clay_tiles', 'plywood', 'over_20_years', 'false', 'good', true, 'low', 'between_5_and_10_years', 'fair', 'fair', true, true, true, '2025-09-26 10:51:16.807-03', '2025-09-26 12:35:06.031-03', '2025-09-26 12:35:06.036-03', 'brayburn@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (279, 139, 10648, 'Sanj Akgan - LA', 'Robert Montanez', 'Sanj Akgan', '949-432-0640', 'feelthedeal007@gmail.com', '136 N Fuller Ave, Los Angeles, CA 90036', 'San Bernardino  ', 'https://www.attic-tech.com/calculator?jobId=10648&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'less_than_5_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'good', false, false, false, '2025-09-26 10:47:06.02-03', '2025-09-26 12:35:06.039-03', '2025-09-26 12:35:06.039-03', 'rmontanez@atticprojects-sb.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (286, 164, 10662, 'Margaret Pettis - GAR', 'Eben Woodall', 'Margaret Pettis', '310-930-5208', 'msmpettis@gmail.com', '13331 Gramercy Pl, Gardena, CA 90249', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10662&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'less_than_5_years', 'true', 'good', false, 'moderate', 'less_than_5_years', 'fair', 'good', false, false, true, '2025-09-26 15:21:30.907-03', '2025-09-26 15:50:59.289-03', '2025-09-26 15:50:59.294-03', 'ebenw43@yahoo.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (280, 138, 10464, 'Vy Dinh - AZU - PMP approved by Tyson ', 'Joe Guerra', 'vy Dinh', '6266896635', 'vydinh1287@gmail.com', '702 E Hanks St, Azusa, CA 91702', 'San Bernardino  ', 'https://www.attic-tech.com/calculator?jobId=10464&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'less_than_5_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'good', false, false, false, '2025-09-26 00:17:12.17-03', '2025-09-26 12:35:06.042-03', '2025-09-26 12:35:06.042-03', 'jguerra@atticprojects-sb.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (282, 168, 10462, 'Amelia Kaune', 'Nathan Woods', 'Amelia Kaune', '206-228-1905', 'ameliakaune@yahoo.com', '3212 NE 85th St, Seattle, WA 98115', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10462&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'less_than_5_years', 'true', 'fair', false, 'high', NULL, NULL, NULL, true, true, true, '2025-09-26 15:45:04.545-03', '2025-09-26 15:50:59.211-03', '2025-09-26 15:50:59.262-03', 'nwoods@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (283, 167, 10665, 'Paul Goodwin - LB', 'Brian Rayburn', 'Paul Goodwin', NULL, 'paulg@acm.org', '6840 E El Progreso St, Long Beach, CA 90815', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10665&page=viewInspectionReport', 'asphalt_shingles', 'slates', 'between_5_and_10_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'good', false, false, false, '2025-09-26 15:43:48.643-03', '2025-09-26 15:50:59.267-03', '2025-09-26 15:50:59.267-03', 'brayburn@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (284, 166, 10664, 'Thiago Marini - BOT', 'Mason Huston', 'Thiago Marini', '425-780-2385', 'thimarini1@gmail.com', '18819 128th Ave NE, Bothell, WA 98011', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10664&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'fair', false, 'high', NULL, NULL, NULL, false, true, false, '2025-09-26 15:42:07.721-03', '2025-09-26 15:50:59.271-03', '2025-09-26 15:50:59.276-03', 'mhuston@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (272, 148, 10531, 'Nave and Marce test', 'Marcelo Sznek', 'Marcelo Nave', '1171624859', 'marce@gmail.com', '2202 Trade St SE, Salem, OR 97301', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10531&page=viewInspectionReport', 'clay_tiles', 'slates', 'between_5_and_10_years', 'true', 'needs_replacement', false, 'moderate', 'between_5_and_10_years', 'needs_replacement', 'fair', false, true, true, '2025-09-26 12:26:53.173-03', '2025-09-26 12:35:05.914-03', '2025-09-26 13:10:43.041-03', 'marcelosz.office@gmail.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (285, 165, 10663, 'Romi Epstein - TAC', 'Patrick Fancher', 'Romi Epstein', '206-300-1775', 'needlegrl@gmail.com', '2121 S Cushman Ave, Tacoma, WA 98405', 'Kent -WA ', 'https://www.attic-tech.com/calculator?jobId=10663&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'fair', false, 'low', 'client_unsure', 'fair', 'fair', false, true, true, '2025-09-26 15:22:52.366-03', '2025-09-26 15:50:59.28-03', '2025-09-26 15:50:59.283-03', 'pfancher@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (281, 152, 1, 'Jessica Conte - YL', 'Joe Guerra', 'Jessica conte', NULL, NULL, '17430 Briardale Ln, Yorba Linda, CA 92886', 'San Bernardino  ', 'https://www.attic-tech.com/calculator?jobId=1&page=viewInspectionReport', 'clay_tiles', 'slates', 'between_5_and_10_years', 'false', 'fair', false, 'high', 'less_than_5_years', 'good', 'good', true, true, true, '2025-09-26 12:54:52.744-03', '2025-09-26 12:56:33.792-03', '2025-09-26 13:11:35.414-03', 'jguerra@atticprojects-sb.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (287, 163, 10661, 'Nancy Bauer - IRV ', 'Vincent Lee', 'Nancy Bauer', '714-317-1518', 'nancynb@earthlink.net', '18 Ensueno W, Irvine, CA 92620', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10661&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'less_than_5_years', 'true', 'good', false, 'moderate', 'less_than_5_years', 'fair', 'fair', false, false, true, '2025-09-26 15:19:11.758-03', '2025-09-26 15:50:59.296-03', '2025-09-26 15:50:59.301-03', 'vincentlee@atticprojects-sb.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (288, 162, 10660, 'Ann Forbes - GLE', 'Eli Musch', 'Ann Forbes', NULL, 'ann.forbes4257@gmail.com', '2429 Sylvan Ln, Glendale, CA 91208', 'Los Angeles', 'https://www.attic-tech.com/calculator?jobId=10660&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_11_and_20_years', 'true', 'good', false, 'high', 'between_5_and_10_years', 'good', 'good', false, false, false, '2025-09-26 15:10:06.652-03', '2025-09-26 15:50:59.305-03', '2025-09-26 15:50:59.305-03', 'emusch@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (289, 161, 10659, 'Carol Ann Fuchser-Burns - OLY', 'Dan Howard ', 'Carol Ann Fuchser', '360-701-6061', 'carol@mycornerincyberspace.com', '407 Logger St SE, Olympia, WA 98503', 'Kent -WA ', 'https://www.attic-tech.com/calculator?jobId=10659&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'good', false, 'moderate', 'between_5_and_10_years', 'good', 'good', false, false, false, '2025-09-26 15:01:25.114-03', '2025-09-26 15:50:59.309-03', '2025-09-26 15:50:59.309-03', 'dhoward@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (290, 160, 10658, 'Nancy Willson - ANA ', 'Brandon LaDue', 'Nancy Willson', '714-833-9198', 'elderconstructionoc@gmail.com', '1336 S Fann St, Anaheim, CA 92804', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10658&page=viewInspectionReport', 'cement_tiles', 'plywood', 'between_5_and_10_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'needs_replacement', false, false, false, '2025-09-26 14:58:34.111-03', '2025-09-26 15:50:59.316-03', '2025-09-26 15:50:59.316-03', 'bladue@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (291, 159, 10657, 'Ann Forbes - GLE', 'Eli Musch', 'Ann Forbes', NULL, 'ann.forbes4257@gmail.com', '2429 Sylvan Ln, Glendale, CA 91208', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10657&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'good', false, false, false, '2025-09-26 14:51:56.413-03', '2025-09-26 15:50:59.322-03', '2025-09-26 15:50:59.322-03', 'emusch@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (292, 158, 10656, 'Linhchi Pham - BELL', 'Jeremy Duplissey', 'Linhchi Pham', '4254490743', 'lcpham26@gmail.com', '4001 133rd Ave SE, Bellevue, WA 98006', 'Kent -WA ', 'https://www.attic-tech.com/calculator?jobId=10656&page=viewInspectionReport', 'metal', 'plywood', 'between_11_and_20_years', 'true', 'good', false, 'high', 'between_11_and_20_years', 'good', 'fair', false, false, false, '2025-09-26 14:46:10.692-03', '2025-09-26 15:50:59.342-03', '2025-09-26 15:50:59.342-03', 'jduplissey@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (293, 157, 10655, 'Bryce Outcault - VIS', 'Richard Ellgen', 'Bryce Outcault', '760-917-7032', 'bryceoutcault@yahoo.com', '1146 Hackamore Rd, Vista, CA 92083', 'San Diego', 'https://www.attic-tech.com/calculator?jobId=10655&page=viewInspectionReport', 'asphalt_shingles', 'slates', 'between_5_and_10_years', 'true', 'good', false, 'high', 'client_unsure', 'good', 'good', false, false, false, '2025-09-26 14:22:10.908-03', '2025-09-26 15:50:59.349-03', '2025-09-26 15:50:59.349-03', 'rellgen@atticprojects-sd.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (294, 156, 10654, 'Roger Root - SNO', 'Richard Barnes', 'Roger Root', '208-301-4900', 'rogerroot@frontier.com', '7631 129th Dr SE Snohomish, WA 98290', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10654&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'good', false, false, false, '2025-09-26 14:15:24.958-03', '2025-09-26 15:50:59.354-03', '2025-09-26 15:50:59.354-03', 'rbarnes@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (295, 155, 10653, 'Teresa Flores - SD', 'Paul Lang', 'Teresa Flores', '858-752-2850', 'tereflores335@gmail.com', '4448 McClintock St, San Diego, CA 92116', 'San Diego', 'https://www.attic-tech.com/calculator?jobId=10653&page=viewInspectionReport', 'asphalt_shingles', 'slates', 'between_11_and_20_years', 'true', 'good', false, 'low', 'over_20_years', 'fair', 'good', false, false, true, '2025-09-26 14:11:10.763-03', '2025-09-26 15:50:59.359-03', '2025-09-26 15:50:59.362-03', 'plang@atticprojects-sd.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (296, 154, 10652, 'Nonie Kleinhans - RED', 'David White', 'Nonie Kleinhans', '909-798-1451', 'nkred@aol.com', '1311 College Ave, Redlands, CA 92374', 'San Bernardino  ', 'https://www.attic-tech.com/calculator?jobId=10652&page=viewInspectionReport', 'asphalt_shingles', 'none', 'less_than_5_years', 'true', 'good', false, 'high', 'less_than_5_years', 'good', 'needs_replacement', false, false, false, '2025-09-26 14:08:51.232-03', '2025-09-26 15:50:59.363-03', '2025-09-26 15:50:59.363-03', 'dwhite@atticprojects-sb.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (297, 153, 10651, 'James Lockvis - ESC', 'Mathew Stevenson', 'James Lockvis', '760-443-8823', 'jlockvis@sbcglobal.net', '2208 Terracewood Ln, Escondido, CA 92026', 'San Diego', 'https://www.attic-tech.com/calculator?jobId=10651&page=viewInspectionReport', 'clay_tiles', 'plywood', 'between_5_and_10_years', 'true', 'fair', false, 'moderate', 'between_11_and_20_years', 'needs_replacement', 'needs_replacement', false, true, true, '2025-09-26 13:57:05.444-03', '2025-09-26 15:50:59.372-03', '2025-09-26 15:50:59.375-03', 'mstevenson@atticprojects-sd.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (274, 146, 10348, 'Ron Smith - LB', 'Brian Rayburn', 'Rob Smith', NULL, 'dadasmith@mac.com', '4125 E Theresa St, Long Beach, CA 90814', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10348&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'over_20_years', 'true', 'needs_replacement', true, 'high', 'less_than_5_years', 'good', 'good', false, true, false, '2025-09-26 11:26:50.686-03', '2025-09-26 12:35:05.999-03', '2025-09-26 15:50:59.383-03', 'brayburn@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (298, 170, 10175, 'Kashif Amin - WOO', 'Mason Huston', 'Kashif Amin', '425-305-7198', 'kashifamin@outlook.com', '18311 171st Ave NE, Woodinville, WA 98072', 'Everett -WA', 'https://www.attic-tech.com/calculator?jobId=10175&page=viewInspectionReport', 'asphalt_shingles', 'plywood', 'between_5_and_10_years', 'true', 'good', false, 'high', 'between_5_and_10_years', 'good', 'good', false, false, false, '2025-09-26 16:26:27.953-03', '2025-09-26 16:29:38.461-03', '2025-09-26 16:29:38.461-03', 'mhuston@atticprojectsseattle.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (299, 169, 10666, 'Mary Haft - OC #4', 'Aaron Gutierrez', 'Mary Haft', '7143457480', 'tendancr@gmail.com', '8315 Milano Dr, Huntington Beach, CA 92646', 'Orange County', 'https://www.attic-tech.com/calculator?jobId=10666&page=viewInspectionReport', 'clay_tiles', 'plywood', 'between_11_and_20_years', 'false', 'needs_replacement', false, 'low', 'over_20_years', 'needs_replacement', 'good', true, true, true, '2025-09-26 16:17:41.357-03', '2025-09-26 16:29:38.562-03', '2025-09-26 16:29:38.566-03', 'agutierrez@atticprojects-oc.com');
INSERT INTO botzilla.inspection_report (id, attic_tech_report_id, attic_tech_estimate_id, estimate_name, salesperson_name, client_name, client_phone, client_email, client_address, branch_name, estimate_link, roof_material, decking_type, roof_age, walkable_roof, roof_condition, full_roof_inspection_interest, customer_comfort, hvac_age, system_condition, air_ducts_condition, full_hvac_furnace_inspection_interest, roof_notification_sent, hvac_notification_sent, attic_tech_created_at, created_at, updated_at, salesperson_email) VALUES (300, 171, 10667, 'Dylan Merkle - RSF', 'Paul Lang', 'Dylan Merkle', '760-710-7307', 'dylan@logansrunconstruction.com', '17040 Circa Del Norte, Rancho Santa Fe, CA 92067', 'San Diego', 'https://www.attic-tech.com/calculator?jobId=10667&page=viewInspectionReport', 'clay_tiles', 'plywood', 'between_5_and_10_years', 'false', 'good', false, 'high', 'between_5_and_10_years', 'good', 'fair', false, false, false, '2025-09-26 16:37:53.273-03', '2025-09-26 16:49:46.29-03', '2025-09-26 16:49:46.29-03', 'plang@atticprojects-sd.com');


--
-- Name: inspection_report_id_seq; Type: SEQUENCE SET; Schema: botzilla; Owner: marce
--

SELECT pg_catalog.setval('botzilla.inspection_report_id_seq', 300, true);


--
-- PostgreSQL database dump complete
--

\unrestrict hYrHpNzxhR0eNNrFOIGAWNmlhwMYBBXbZxVwa3IEjmtLmBGGplzHE27y9YHp9Zf

